public class HandsetRunner {
    public static void main(String[] args) {
        long number;

        number = Handset.getContactNumberByName("Alex");
        System.out.println("Phone number of Alex: " + number);
        number = Handset.getContactNumberByName("Ben");
        System.out.println("Phone number of Ben: " + number);
        number = Handset.getContactNumberByName("Charlie");
        System.out.println("Phone number of Charlie: " + number);
        number = Handset.getContactNumberByName("David");
        System.out.println("Phone number of David: " + number);
        number = Handset.getContactNumberByName("Ethan");
        System.out.println("Phone number of Ethan: " + number);
        number = Handset.getContactNumberByName("Frank");
        System.out.println("Phone number of Frank: " + number);
        number = Handset.getContactNumberByName("George");
        System.out.println("Phone number of George: " + number);
        number = Handset.getContactNumberByName("Harry");
        System.out.println("Phone number of Harry: " + number);
        number = Handset.getContactNumberByName("Ian");
        System.out.println("Phone number of Ian: " + number);
        number = Handset.getContactNumberByName("Jack");
        System.out.println("Phone number of Jack: " + number);
        number = Handset.getContactNumberByName("Kevin");
        System.out.println("Phone number of Kevin: " + number);
        number = Handset.getContactNumberByName("Liam");
        System.out.println("Phone number of Liam: " + number);
        number = Handset.getContactNumberByName("Mason");
        System.out.println("Phone number of Mason: " + number);
        number = Handset.getContactNumberByName("Noah");
        System.out.println("Phone number of Noah: " + number);
        number = Handset.getContactNumberByName("Owen");
        System.out.println("Phone number of Owen: " + number);
        number = Handset.getContactNumberByName("Paul");
        System.out.println("Phone number of Paul: " + number);
        number = Handset.getContactNumberByName("Quinn");
        System.out.println("Phone number of Quinn: " + number);
        number = Handset.getContactNumberByName("Ryan");
        System.out.println("Phone number of Ryan: " + number);
        number = Handset.getContactNumberByName("Sean");
        System.out.println("Phone number of Sean: " + number);
        number = Handset.getContactNumberByName("Tom");
        System.out.println("Phone number of Tom: " + number);
        number = Handset.getContactNumberByName("Umar");
        System.out.println("Phone number of Umar: " + number);
        number = Handset.getContactNumberByName("Viktor");
        System.out.println("Phone number of Viktor: " + number);
        number = Handset.getContactNumberByName("Will");
        System.out.println("Phone number of Will: " + number);
        number = Handset.getContactNumberByName("Xavier");
        System.out.println("Phone number of Xavier: " + number);
        number = Handset.getContactNumberByName("Yusuf");
        System.out.println("Phone number of Yusuf: " + number);
        number = Handset.getContactNumberByName("Zane");
        System.out.println("Phone number of Zane: " + number);
        number = Handset.getContactNumberByName("Aiden");
        System.out.println("Phone number of Aiden: " + number);
        number = Handset.getContactNumberByName("Bryan");
        System.out.println("Phone number of Bryan: " + number);
        number = Handset.getContactNumberByName("Caleb");
        System.out.println("Phone number of Caleb: " + number);
        number = Handset.getContactNumberByName("Dylan");
        System.out.println("Phone number of Dylan: " + number);
        number = Handset.getContactNumberByName("Eli");
        System.out.println("Phone number of Eli: " + number);
        number = Handset.getContactNumberByName("Finn");
        System.out.println("Phone number of Finn: " + number);
        number = Handset.getContactNumberByName("Gabe");
        System.out.println("Phone number of Gabe: " + number);
        number = Handset.getContactNumberByName("Hank");
        System.out.println("Phone number of Hank: " + number);
        number = Handset.getContactNumberByName("Isaac");
        System.out.println("Phone number of Isaac: " + number);
        number = Handset.getContactNumberByName("Joel");
        System.out.println("Phone number of Joel: " + number);
        number = Handset.getContactNumberByName("Kyle");
        System.out.println("Phone number of Kyle: " + number);
        number = Handset.getContactNumberByName("Luke");
        System.out.println("Phone number of Luke: " + number);
        number = Handset.getContactNumberByName("Mark");
        System.out.println("Phone number of Mark: " + number);
        number = Handset.getContactNumberByName("Nate");
        System.out.println("Phone number of Nate: " + number);
        number = Handset.getContactNumberByName("Oscar");
        System.out.println("Phone number of Oscar: " + number);
        number = Handset.getContactNumberByName("Pete");
        System.out.println("Phone number of Pete: " + number);
        number = Handset.getContactNumberByName("Quincy");
        System.out.println("Phone number of Quincy: " + number);
        number = Handset.getContactNumberByName("Russ");
        System.out.println("Phone number of Russ: " + number);
        number = Handset.getContactNumberByName("Sam");
        System.out.println("Phone number of Sam: " + number);
        number = Handset.getContactNumberByName("Toby");
        System.out.println("Phone number of Toby: " + number);
        number = Handset.getContactNumberByName("Uri");
        System.out.println("Phone number of Uri: " + number);
        number = Handset.getContactNumberByName("Vince");
        System.out.println("Phone number of Vince: " + number);
        number = Handset.getContactNumberByName("Wade");
        System.out.println("Phone number of Wade: " + number);
        number = Handset.getContactNumberByName("Xander");
        System.out.println("Phone number of Xander: " + number);
        number = Handset.getContactNumberByName("Yanni");
        System.out.println("Phone number of Yanni: " + number);
        number = Handset.getContactNumberByName("Zack");
        System.out.println("Phone number of Zack: " + number);
        number = Handset.getContactNumberByName("Amber");
        System.out.println("Phone number of Amber: " + number);
        number = Handset.getContactNumberByName("Bella");
        System.out.println("Phone number of Bella: " + number);
        number = Handset.getContactNumberByName("Clara");
        System.out.println("Phone number of Clara: " + number);
        number = Handset.getContactNumberByName("Daisy");
        System.out.println("Phone number of Daisy: " + number);
        number = Handset.getContactNumberByName("Ella");
        System.out.println("Phone number of Ella: " + number);
        number = Handset.getContactNumberByName("Fiona");
        System.out.println("Phone number of Fiona: " + number);
        number = Handset.getContactNumberByName("Gina");
        System.out.println("Phone number of Gina: " + number);
    }
}
