public class Bank {
     static String name;
     static String branchCode;
     static String address;
     static String swiftCode;
     static double interestRate;
     static int ifscCode;
     static String manager;
     static int employees;
     static boolean openOnWeekends;
     static double atmCash;
     static boolean onlineBanking;
     static String supportEmail;
     static String helpline;
     static int branches;
     static String established;
     static boolean fdAllowed;
     static double atmLimit;
     static String currency;

    public static void main(String[] args) {
        System.out.println("name = " + name);
        System.out.println("branchCode = " + branchCode);
        System.out.println("address = " + address);
        System.out.println("swiftCode = " + swiftCode);
        System.out.println("interestRate = " + interestRate);
        System.out.println("ifscCode = " + ifscCode);
        System.out.println("manager = " + manager);
        System.out.println("employees = " + employees);
        System.out.println("openOnWeekends = " + openOnWeekends);
        System.out.println("atmCash = " + atmCash);
        System.out.println("onlineBanking = " + onlineBanking);
        System.out.println("supportEmail = " + supportEmail);
        System.out.println("helpline = " + helpline);
        System.out.println("branches = " + branches);
        System.out.println("established = " + established);
        System.out.println("fdAllowed = " + fdAllowed);
        System.out.println("atmLimit = " + atmLimit);
        System.out.println("currency = " + currency);
     name = "Global Bank";
     branchCode = "GB001";
     address = "VIJAYNAGAR";
      swiftCode = "GBSWIFTXX";
      interestRate = 3.5;
      ifscCode = 123456;
      manager = "Jane Doe";
      employees = 150;
      openOnWeekends = false;
      atmCash = 500000;
      onlineBanking = true;
      supportEmail = "support@bank.com";
      helpline = "1800-BANK";
      branches = 50;
      established = "1980-01-01";
     fdAllowed = true;
    atmLimit = 25000;
    currency = "USD";
        System.out.println("name = " + name);
        System.out.println("branchCode = " + branchCode);
        System.out.println("address = " + address);
        System.out.println("swiftCode = " + swiftCode);
        System.out.println("interestRate = " + interestRate);
        System.out.println("ifscCode = " + ifscCode);
        System.out.println("manager = " + manager);
        System.out.println("employees = " + employees);
        System.out.println("openOnWeekends = " + openOnWeekends);
        System.out.println("atmCash = " + atmCash);
        System.out.println("onlineBanking = " + onlineBanking);
        System.out.println("supportEmail = " + supportEmail);
        System.out.println("helpline = " + helpline);
        System.out.println("branches = " + branches);
        System.out.println("established = " + established);
        System.out.println("fdAllowed = " + fdAllowed);
        System.out.println("atmLimit = " + atmLimit);
        System.out.println("currency = " + currency);
    }
}
