public class Desktop {
     static String brand;
     static String model;
     static String processor;
     static int ramGB;
     static int storageGB;
     static String storageType;
     static boolean hasWifi;
     static boolean hasBluetooth;
     static String os ;
     static String graphicsCard;
     static int usbPorts;
     static boolean hasHDMI;
     static boolean hasVGA;
     static boolean isTouchscreen;
     static double weightKg;
     static String color;
     static double priceUSD;
     static int warrantyYears;
     static boolean hasDVDDrive;
     static String powerSupply;

    public static void main(String[] args) {
        System.out.println("brand = " + brand);
        System.out.println("model = " + model);
        System.out.println("processor = " + processor);
        System.out.println("ramGB = " + ramGB);
        System.out.println("storageGB = " + storageGB);
        System.out.println("storageType = " + storageType);
        System.out.println("hasWifi = " + hasWifi);
        System.out.println("hasBluetooth = " + hasBluetooth);
        System.out.println("os = " + os);
        System.out.println("graphicsCard = " + graphicsCard);
        System.out.println("usbPorts = " + usbPorts);
        System.out.println("hasHDMI = " + hasHDMI);
        System.out.println("hasVGA = " + hasVGA);
        System.out.println("isTouchscreen = " + isTouchscreen);
        System.out.println("weightKg = " + weightKg);
        System.out.println("color = " + color);
      brand = "Dell";
      model = "OptiPlex 5090";
      processor = "Intel Core i7";
      ramGB = 16;
      storageGB = 512;
      storageType = "SSD";
      hasWifi = true;
      hasBluetooth = true;
      os = "Windows 11";
     graphicsCard = "NVIDIA GTX 1650";
      usbPorts = 6;
      hasHDMI = true;
      hasVGA = false;
      isTouchscreen = false;
     weightKg = 5.5;
      color = "Black";
      priceUSD = 899.99;
      warrantyYears = 3;
      hasDVDDrive = false;
      powerSupply = "500W";
        System.out.println("brand = " + brand);
        System.out.println("model = " + model);
        System.out.println("processor = " + processor);
        System.out.println("ramGB = " + ramGB);
        System.out.println("storageGB = " + storageGB);
        System.out.println("storageType = " + storageType);
        System.out.println("hasWifi = " + hasWifi);
        System.out.println("hasBluetooth = " + hasBluetooth);
        System.out.println("os = " + os);
        System.out.println("graphicsCard = " + graphicsCard);
        System.out.println("usbPorts = " + usbPorts);
        System.out.println("hasHDMI = " + hasHDMI);
        System.out.println("hasVGA = " + hasVGA);
        System.out.println("isTouchscreen = " + isTouchscreen);
        System.out.println("weightKg = " + weightKg);
        System.out.println("color = " + color);

        }}
