public class Satellite {
     static String name;
     static double orbitalAltitudeKm;
     static double massKg;
     static String purpose;
     static String launchDate;
     static String operator;
     static double powerWatts;
     static boolean hasCamera;
     static boolean hasRadar;
     static String launchVehicle;
     static String status;
     static double expectedLifespanYears;
     static String orbitType;
     static boolean isGeostationary;
     static double inclinationDeg;
     static String groundStation;
     static double dataRateMbps;
     static boolean hasAutopilot;
     static String manufacturer;

    public static void main(String[] args) {
        System.out.println("name = " + name);
        System.out.println("orbitalAltitudeKm = " + orbitalAltitudeKm);
        System.out.println("massKg = " + massKg);
        System.out.println("purpose = " + purpose);
        System.out.println("launchDate = " + launchDate);
        System.out.println("operator = " + operator);
        System.out.println("powerWatts = " + powerWatts);
        System.out.println("hasCamera = " + hasCamera);
        System.out.println("hasRadar = " + hasRadar);
        System.out.println("launchVehicle = " + launchVehicle);
        System.out.println("status = " + status);
        System.out.println("expectedLifespanYears = " + expectedLifespanYears);
        System.out.println("orbitType = " + orbitType);
        System.out.println("isGeostationary = " + isGeostationary);
        System.out.println("inclinationDeg = " + inclinationDeg);
        System.out.println("groundStation = " + groundStation);
        System.out.println("dataRateMbps = " + dataRateMbps);
        System.out.println("hasAutopilot = " + hasAutopilot);
        System.out.println("manufacturer = " + manufacturer);
     name = "Orbital One";
     orbitalAltitudeKm = 550.5;
     massKg = 1200.0;
     purpose = "Earth Observation";
    launchDate = "2022-07-15";
     operator = "SpaceTech Co.";
      powerWatts = 1500;
     hasCamera = true;
    hasRadar = false;
     launchVehicle = "Falcon 9";
      status = "Operational";
      expectedLifespanYears = 7.5;
      orbitType = "LEO";
      isGeostationary = false;
     inclinationDeg = 97.0;
    groundStation = "GS-Alpha";
     dataRateMbps = 50.0;
      hasAutopilot = true;
   manufacturer = "SpaceTech";
        System.out.println("name = " + name);
        System.out.println("orbitalAltitudeKm = " + orbitalAltitudeKm);
        System.out.println("massKg = " + massKg);
        System.out.println("purpose = " + purpose);
        System.out.println("launchDate = " + launchDate);
        System.out.println("operator = " + operator);
        System.out.println("powerWatts = " + powerWatts);
        System.out.println("hasCamera = " + hasCamera);
        System.out.println("hasRadar = " + hasRadar);
        System.out.println("launchVehicle = " + launchVehicle);
        System.out.println("status = " + status);
        System.out.println("expectedLifespanYears = " + expectedLifespanYears);
        System.out.println("orbitType = " + orbitType);
        System.out.println("isGeostationary = " + isGeostationary);
        System.out.println("inclinationDeg = " + inclinationDeg);
        System.out.println("groundStation = " + groundStation);
        System.out.println("dataRateMbps = " + dataRateMbps);
        System.out.println("hasAutopilot = " + hasAutopilot);
        System.out.println("manufacturer = " + manufacturer);

    }
}
