public class Stadium {
     static String name;
     static String location;
     static int capacity;
     static String sportType;
     static boolean hasRoof;
     static boolean floodlights;
     static int yearBuilt;
     static String surfaceType;
     static boolean isMultipurpose;
     static String owner;
     static double areaSqFt;
     static boolean hasVIPBox;
     static boolean hasScoreboard;
     static int parkingSpots;
     static boolean hasMetroAccess;
     static boolean hasFoodCourt;
     static boolean hasMedicalRoom;
     static String architect;
     static String contact;

    public static void main(String[] args) {
        System.out.println("name = " + name);
        System.out.println("location = " + location);
        System.out.println("capacity = " + capacity);
        System.out.println("sportType = " + sportType);
        System.out.println("hasRoof = " + hasRoof);
        System.out.println("floodlights = " + floodlights);
        System.out.println("yearBuilt = " + yearBuilt);
        System.out.println("surfaceType = " + surfaceType);
        System.out.println("isMultipurpose = " + isMultipurpose);
        System.out.println("owner = " + owner);
        System.out.println("areaSqFt = " + areaSqFt);
        System.out.println("hasVIPBox = " + hasVIPBox);
        System.out.println("hasScoreboard = " + hasScoreboard);
        System.out.println("parkingSpots = " + parkingSpots);
        System.out.println("hasMetroAccess = " + hasMetroAccess);
        System.out.println("hasFoodCourt = " + hasFoodCourt);
        System.out.println("hasMedicalRoom = " + hasMedicalRoom);
        System.out.println("architect = " + architect);
        System.out.println("contact = " + contact);
    name = "National Arena";
     location = "City Central";
     capacity = 70000;
      sportType = "Football";
     hasRoof = true;
    floodlights = true;
     yearBuilt = 1998;
     surfaceType = "Grass";
    isMultipurpose = true;
     owner = "City Sports Authority";
     areaSqFt = 250000;
     hasVIPBox = true;
      hasScoreboard = true;
     parkingSpots = 2000;
     hasMetroAccess = true;
     hasFoodCourt = true;
     hasMedicalRoom = true;
     architect = "DesignCo";
     contact = "stadium@arena.com";
     System.out.println("name = " + name);
        System.out.println("location = " + location);
        System.out.println("capacity = " + capacity);
        System.out.println("sportType = " + sportType);
        System.out.println("hasRoof = " + hasRoof);
        System.out.println("floodlights = " + floodlights);
        System.out.println("yearBuilt = " + yearBuilt);
        System.out.println("surfaceType = " + surfaceType);
        System.out.println("isMultipurpose = " + isMultipurpose);
        System.out.println("owner = " + owner);
        System.out.println("areaSqFt = " + areaSqFt);
        System.out.println("hasVIPBox = " + hasVIPBox);
        System.out.println("hasScoreboard = " + hasScoreboard);
        System.out.println("parkingSpots = " + parkingSpots);
        System.out.println("hasMetroAccess = " + hasMetroAccess);
        System.out.println("hasFoodCourt = " + hasFoodCourt);
        System.out.println("hasMedicalRoom = " + hasMedicalRoom);
        System.out.println("architect = " + architect);
        System.out.println("contact = " + contact);

    }
}
