public class SwitchBoard {
     static int totalSwitches;
     static String manufacturer;
     static boolean isSmart;
     static String model;
     static String voltage;
     static int currentRating;
     static boolean hasIndicator;
     static String color;
     static double weight;
     static String material;
     static boolean waterproof;
     static String installationType;
     static int warrantyMonths;
     static String serialNumber;
     static double price;
     static String countryOfOrigin;
     static boolean isROHSCompliant;
     static String protectionClass;

    public static void main(String[] args) {
        System.out.println("totalSwitches = " + totalSwitches);
        System.out.println("manufacturer = " + manufacturer);
        System.out.println("isSmart = " + isSmart);
        System.out.println("model = " + model);
        System.out.println("voltage = " + voltage);
        System.out.println("currentRating = " + currentRating);
        System.out.println("hasIndicator = " + hasIndicator);
        System.out.println("color = " + color);
        System.out.println("weight = " + weight);
        System.out.println("material = " + material);
        System.out.println("waterproof = " + waterproof);
        System.out.println("installationType = " + installationType);
        System.out.println("warrantyMonths = " + warrantyMonths);
        System.out.println("serialNumber  " + serialNumber);
        System.out.println("price = " + price);
        System.out.println("countryOfOrigin = " + countryOfOrigin);
        System.out.println("isROHSCompliant = " + isROHSCompliant);
        System.out.println("protectionClass = " + protectionClass);
 totalSwitches = 10;
      manufacturer = "ElectroCo";
      isSmart = true;
      model = "SB-1000";
     voltage = "240V";
      currentRating = 16;
     hasIndicator = true;
     color = "White";
     weight = 0.5;
      material = "Plastic";
      waterproof = false;
      installationType = "Wall-mounted";
      warrantyMonths = 24;
      serialNumber = "SN12345";
      price = 29.99;
     countryOfOrigin = "India";
      isROHSCompliant = true;
      protectionClass = "IP20";
    System.out.println("totalSwitches = " + totalSwitches);
        System.out.println("manufacturer = " + manufacturer);
        System.out.println("isSmart = " + isSmart);
        System.out.println("model = " + model);
        System.out.println("voltage = " + voltage);
        System.out.println("currentRating = " + currentRating);
        System.out.println("hasIndicator = " + hasIndicator);
        System.out.println("color = " + color);
        System.out.println("weight = " + weight);
        System.out.println("material = " + material);
        System.out.println("waterproof = " + waterproof);
        System.out.println("installationType = " + installationType);
        System.out.println("warrantyMonths = " + warrantyMonths);
        System.out.println("serialNumber  " + serialNumber);
        System.out.println("price = " + price);
        System.out.println("countryOfOrigin = " + countryOfOrigin);
        System.out.println("isROHSCompliant = " + isROHSCompliant);
        System.out.println("protectionClass = " + protectionClass);
    }
}
